### ISSUE TITLE
format of the advisories on main page cause incorrect assumptions

### ISSUE THREAD

**Issue by prmarino1** [heimdal/h5lweb#10]
All of the advisories listed on the main page have been patched as far as i can tell, and some of them refer to old versions. this isn't made clear on first glance at the site. as a result it can make non technical manager who google Heimdal draw incorrect conclusions about its security.
it should be made more clear that they apply version prior to x.y on that page.

**Comment by quanah** [comment]
Hi,

I would note that clicking on an advisory expands it with more information, which includes exactly what version(s) are affected.  I agree the format is somewhat of a pain, and I'll look into making it so the version information is more easily visible.
