### ISSUE TITLE
Git instructions wrong and not up to date.

### ISSUE THREAD

**Issue by hbhotz** [heimdal/h5lweb#18]
I was setting up a source tree on a new VM and was reminded of some problems with git and our instructions on <http://www.h5l.org/sources.html>. 

First of all the form given for doing a read-only clone of the repository doesn’t work (and AFAICR never has). If you’re not logging in with your own git account then the form that works is 

git clone git://github.com/heimdal/heimdal.git

Second of all there appears to have been a 7.2 release. Perhaps Nico just hasn’t finished yet, but a) it’s not mentioned on that web page and b) simply s/7-1/7-2/g doesn’t work.

**Comment by quanah** [comment]
IIRC, it was never intended for 7.2 to be announced (I.e., that was by design), which is why I haven't updated the website to reference it specifically.

**Comment by hbhotz** [comment]
Understood. I don’t recall we ever announced minor versions. I still think the web page(s) should be kept current though. Just my opinion.

> On Apr 12, 2017, at 12:06 PM, Quanah Gibson-Mount <notifications@github.com> wrote:
> 
> IIRC, it was never intended for 7.2 to be announced (I.e., that was by design), which is why I haven't updated the website to reference it specifically.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Personal email.  hbhotz@oxy.edu

**Comment by nicowilliams** [comment]
On Wed, Apr 12, 2017 at 12:45:43PM -0700, Henry B Hotz wrote:
> Understood. I don’t recall we ever announced minor versions. I still
> think the web page(s) should be kept current though. Just my opinion.

The announcement for 7.2 was meant to go out.  By some accident, it
didn't.
