### ISSUE TITLE
https broken for h5l.org

### ISSUE THREAD

**Issue by quanah** [heimdal/h5lweb#6]
There appears to be something fundamentally broken with the https setup for h5l.org:

quanah@ub16:~$ openssl s_client -connect www.h5l.org:443
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 305 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1480536467
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---

**Comment by lha** [comment]
Dunno what was wrong, a restart helped.

Love

**Comment by vdukhovni** [comment]
Thanks.  Speaking of infrastructure, the mailing list web server seems to be gone.  There is no longer list.sics.se.  While the "-request" address still works, it would be good to have the HTTP UI also up and running...  For now the links to heimdal-announce and heimdal-discuss at https://www.h5l.org/ are broken:

```

	<h3>Mail</h3>

	There are two mailings lists:
	<a href="https://list.sics.se/sympa/info/heimdal-announce">heimdal-announce</a> and
	<a href="https://list.sics.se/sympa/info/heimdal-discuss">heimdal-discuss</a>
	(<a href="https://list.sics.se/sympa/arc/heimdal-discuss">ml-archive</a>,
	<a href="http://www.mail-archive.com/heimdal-discuss@sics.se/">mail-archive</a>,
	<a href="http://news.gmane.org/gmane.comp.encryption.kerberos.heimdal.general">gmane</a>).
```

**Comment by quanah** [comment]
@vdukhovni Yes, that's issue#5.

**Comment by lha** [comment]
Lots of quoting errors in those lovely xml files.

Love
